### ISSUE TITLE
Support Dark Mode

### ISSUE THREAD

**Issue by ryonakano** [ryonakano/konbucase#18]
![Screenshot from 2020-04-03 20-01-22](https://user-images.githubusercontent.com/26003928/78353940-ec431000-75e5-11ea-90dc-30c68d52edbb.png)

The background color of the text view is hard-coded so that it does look bad in Dark Mode.

**Comment by cassidyjames** [comment]
To be fair, elementary OS doesn't have a dark mode yet so issues like this are expected when changing out the stylesheet from underneath apps or using unsupported GTK hacks.
