### ISSUE TITLE
Recalculate when changing combobox

### ISSUE THREAD

**Issue by cassidyjames** [ryonakano/konbucase#26]
it looks like you recalculate the conversion when typing in the entry, but it would be handy to recalculate it when changing the combox(es) as well.

**Comment by ryonakano** [comment]
Seems like a regression of 733a6e5 :sweat:

**Comment by cassidyjames** [comment]
@ryonakano would you like us to hold off finishing the review of Konbucase until a new release is made, or are you fine with us continuing the review as-is for the 0.1.0 release?

**Comment by ryonakano** [comment]
@cassidyjames I'll make a new release soon so I'd like you to postpone the review of Konbucase until then.

**Comment by cassidyjames** [comment]
@ryonakano will do.
