### ISSUE TITLE
Idea for a (possibly) better UI

### ISSUE THREAD

**Issue by Fatih20** [ryonakano/konbucase#43]
![KonbuCase Criticism](https://user-images.githubusercontent.com/51940383/84892066-1ecdb680-b0c7-11ea-9a9a-b89cabf56388.png)
It's far more intuitive, require less text, require less eye movement for the user. What do you think?

**Comment by ryonakano** [comment]
![Screenshot from 2020-06-17 20-58-47](https://user-images.githubusercontent.com/26003928/84895584-7d059400-b0dd-11ea-96ec-b3bdac5fdc80.png)

You're right, in some blog services that you write in Markdown this layout seems to be well-known and reasonable.
