### ISSUE TITLE
Improving the Konbucase Icon

### ISSUE THREAD

**Issue by Fatih20** [ryonakano/konbucase#45]
My complains about the previous icons is the gradient is too sharp. Gradient is used in elementary to make the icon look skeuomorphic. Here, it's used for lighting on the objects in question. However, too sharp of a gradient would make the object look like it's gradient colored, instead of solid colored with light coming from the top (which is the desired effects). Other than that, the arrow feels like it's too thin and small, which makes it a bit imperceptible as an arrow. This is an improved version I've made. If this is approved, I'll make the pull request.

![com (copy) github ryonakano konbucase](https://user-images.githubusercontent.com/51940383/85920853-8511c080-b8a1-11ea-94b4-f46b58b7159b.png)
![Screenshot from 2020-06-27 17 57 20](https://user-images.githubusercontent.com/51940383/85920850-7fb47600-b8a1-11ea-9ddd-db0d31a2fece.png)

**Comment by ryonakano** [comment]
Looks fine, waiting for the PR!

**Comment by ryonakano** [comment]
Fixed in #46. @Fatih20 Thank you very much!
